### ISSUE TITLE
Allow callback= to be an awaitable function

### ISSUE THREAD

**Issue by simonw** [simonw/asgi-cors#4]
If `callback=` could be provided an awaitable, users could construct functions that e.g. make an async call to a database as part of deciding if a host should be allowed.

I tried implementing this with a `asyncio.isawaitable()` test against the callable but for some reason it didn't detect my await function as being awaitable. Here's the unit test I added which I failed to get passing:

```python

@pytest.mark.asyncio
async def test_callback_async():
    was_called = False

    async def callback_true(origin):
        return True

    async def callback_false(origin):
        return False

    assert EXAMPLE_HOST == await get_cors_header(asgi_cors(hello_world_app, callback=callback_true), EXAMPLE_HOST)
    assert None == await get_cors_header(asgi_cors(hello_world_app, callback=callback_false), EXAMPLE_HOST)
```

**Comment by dmgolembiowski** [comment]
@simonw Admittedly, this might not be much help to you (or relevant anymore) but would changing `asyncio.iscoroutine(...)` to `asyncio.iscoroutinefunction(...)` fix the issue?
